enum ErrorTypes {
  USERNAME_OR_PASSWORD_IS_REQUIRED = 0,
  USERNAME_EXISTS = 1,
  USERNAME_NOT_EXISTS = 2,
  PASSWORD_ERROR = 3,
  UNAUTHORIZATION = 4,
  REQUIRE_HAVA_VALUE = 5,
  EXIST_GOOD = 6,
  NOT_EXIST_GOOD = 7,
  OVER_LIMIT = 8,
  EXIST_POSITION = 9,
  NOT_EXIST_POSITION = 10,
  NOT_DELETE_POSITION = 11,
  OLD_PASSWORD_ERROR = 12
}

export default ErrorTypes
